version: '3.8'

services:
  # API Service
  api:
    build:
      context: ../backend
      dockerfile: ../docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ../backend:/app
    networks:
      - universalmigrate-network

  # Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    depends_on:
      - api
    networks:
      - universalmigrate-network

  # Database for storing configurations, user data, etc.
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=universalmigrate
      - POSTGRES_PASSWORD=universalmigrate
      - POSTGRES_DB=universalmigrate
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - universalmigrate-network

  # Redis for caching and job queues
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - universalmigrate-network

networks:
  universalmigrate-network:

volumes:
  postgres-data:
